#!/bin/sh

rm ca-key.pem ca.csr ca.pem consul-key.pem consul.csr consul.pem
kubectl delete statefulset consul
kubectl delete pvc data-consul-0 data-consul-1 data-consul-2
kubectl delete svc consul
kubectl delete jobs consul-join
kubectl delete secrets consul
kubectl delete configmaps consul
