#!/bin/sh

kubectl delete statefulset consul
kubectl delete pvc data-consul-0 data-consul-1 data-consul-2
kubectl delete svc consul consul-http
kubectl delete jobs consul-join
kubectl delete secrets consul
kubectl delete configmaps consul
